---
trigger: 
  - master

pr:
  branches:
    include:
    - master

stages:
- stage: precheck
  jobs:
    - job: spellcheck
      dependsOn: []
      pool:
        vmImage: "ubuntu-18.04"
      steps:
        - script: scripts/spellcheck.sh
