---
trigger: 
  - master

pr:
  branches:
    include:
    - master

stages:
- stage: precheck
  jobs:
    - job: govet
      dependsOn: []
      pool:
        vmImage: "ubuntu-18.04"
      steps:
        - task: GoTool@0
          inputs:
            version: '1.16'
        - task: Go@0
          inputs:
            command: 'custom'
            customCommand: 'vet'
