trigger: 
  - master

pr:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: applicationName
  value: k8s-secret-injector
- name: imageName
  value: 'quay.io/opstree/k8s-secret-injector'

stages:
- stage: CodeStability
  jobs:
  - job:
    displayName: CodeStability
    steps:
    - task: GoTool@0
      displayName: "Installing golang => 1.16"
      inputs:
        version: '1.16'

    - task: Go@0
      displayName: "Downloading project dependencies"
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: Go@0
      displayName: "Building project"
      inputs:
        command: 'build'
        arguments: '-o $(applicationName)'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

- stage: CodeQuality
  jobs:
  - job:
    displayName: CodeQuality
    steps:
    - script: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.40.0
        golangci-lint run ./...
