trigger: 
  - master
  - gcp

pr:
  branches:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Code stability
  jobs:
  - job:
    steps:
    - task: GoTool@0
      displayName: "Installing golang => 1.16.0"
      inputs:
        version: '1.16.0'

    - task: Go@0
      displayName: "Downloading project dependencies"
      inputs:
        command: 'get'
        arguments: '-d'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: Go@0
      displayName: "Building project"
      inputs:
        command: 'build'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
